### ISSUE TITLE
bigip_pool_member can't add existing node in route domain to a pool

### ISSUE THREAD

**Issue by lindeskar** [F5Networks/f5-ansible#887]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_pool_member

##### ANSIBLE VERSION
```
ansible 2.6.3
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/vagrant/library/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION
```
Python 2.7.12
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Wed Feb 21 10:51:40 PST 2018
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.18
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`bigip_pool_member` can't add an existing node to a pool if it's in a route domain other than 0. Having the module create a new node is working fine.

There is no issue adding an existing node if it's in route domain 0.

This seem to be the root cause of #823. Opening new ticket from [comment](https://github.com/F5Networks/f5-ansible/issues/823#issuecomment-413205749).

Please see the below for possible root cause.

##### STEPS TO REPRODUCE
1. Create a node in a route domain other than 0 on device or using `bigip_node`.
2. Add it as a pool member with `bigip_pool_member`.

```
---

- name: bigip_pool_member route domain issue
  hosts: f5-demo-1.local
  gather_facts: no
  connection: local
  tasks:

    - name: Create node
      bigip_node:
        provider: "{{ f5_provider }}"
        name: test_node
        partition: test_partition # Partition Default Route Domain = 5
        address: 1.2.3.4

    - name: Create pool
      bigip_pool:
        provider: "{{ f5_provider }}"
        name: test_pool
        partition: test_partition

    - name: Add pool member
      bigip_pool_member:
        provider: "{{ f5_provider }}"
        pool: test_pool
        partition: test_partition
        name: test_node
        port: 8080
```

##### EXPECTED RESULTS
The existing node to be added as a member to the pool.

##### ACTUAL RESULTS
The member is not added to the pool and `F5ModuleError` is raised.

```
ansible-playbook 2.6.3
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/vagrant/library/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /vagrant/ansible.cfg as config file
setting up inventory plugins
Parsed /vagrant/inventories/private inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: pool_member_issue.yml ******************************************************************************************************************************************
1 plays in pool_member_issue.yml

PLAY [bigip_pool_member route domain issue] ******************************************************************************************************************************
META: ran handlers

TASK [Create node] *******************************************************************************************************************************************************
task path: /vagrant/pool_member_issue.yml:10
<172.16.252.51> connection transport is rest
<172.16.252.51> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<172.16.252.51> EXEC /bin/sh -c 'echo ~vagrant && sleep 0'
<172.16.252.51> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1535209218.57-64342124754219 `" && echo ansible-tmp-1535209218.57-64342124754219="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1535209218.57-64342124754219 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_node.py
<172.16.252.51> PUT /home/vagrant/.ansible/tmp/ansible-local-11247lepylU/tmpqGnnON TO /home/vagrant/.ansible/tmp/ansible-tmp-1535209218.57-64342124754219/bigip_node.py
<172.16.252.51> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1535209218.57-64342124754219/ /home/vagrant/.ansible/tmp/ansible-tmp-1535209218.57-64342124754219/bigip_node.py && sleep 0'
<172.16.252.51> EXEC /bin/sh -c '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1535209218.57-64342124754219/bigip_node.py && sleep 0'
<172.16.252.51> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1535209218.57-64342124754219/ > /dev/null 2>&1 && sleep 0'
changed: [f5-demo-1.local] => {
    "changed": true, 
    "fqdn": {
        "autopopulate": "enabled", 
        "downInterval": "5", 
        "interval": "3600"
    }, 
    "fqdn_address_type": "ipv4", 
    "fqdn_auto_populate": "enabled", 
    "fqdn_down_interval": "5", 
    "fqdn_up_interval": "3600", 
    "invocation": {
        "module_args": {
            "address": "1.2.3.4", 
            "description": null, 
            "fqdn": null, 
            "fqdn_address_type": null, 
            "fqdn_auto_populate": null, 
            "fqdn_down_interval": null, 
            "fqdn_up_interval": null, 
            "monitor_type": null, 
            "monitors": null, 
            "name": "test_node", 
            "partition": "test_partition", 
            "password": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "172.16.252.51", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "session": "user-enabled", 
    "state": "user-up"
}

TASK [Create pool] *******************************************************************************************************************************************************
task path: /vagrant/pool_member_issue.yml:17
<172.16.252.51> connection transport is rest
<172.16.252.51> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<172.16.252.51> EXEC /bin/sh -c 'echo ~vagrant && sleep 0'
<172.16.252.51> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.23-72673795000305 `" && echo ansible-tmp-1535209219.23-72673795000305="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.23-72673795000305 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool.py
<172.16.252.51> PUT /home/vagrant/.ansible/tmp/ansible-local-11247lepylU/tmpwk4XYE TO /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.23-72673795000305/bigip_pool.py
<172.16.252.51> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.23-72673795000305/ /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.23-72673795000305/bigip_pool.py && sleep 0'
<172.16.252.51> EXEC /bin/sh -c '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.23-72673795000305/bigip_pool.py && sleep 0'
<172.16.252.51> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.23-72673795000305/ > /dev/null 2>&1 && sleep 0'
changed: [f5-demo-1.local] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "description": null, 
            "lb_method": null, 
            "metadata": null, 
            "monitor_type": null, 
            "monitors": null, 
            "name": "test_pool", 
            "partition": "test_partition", 
            "password": null, 
            "priority_group_activation": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "172.16.252.51", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "reselect_tries": null, 
            "server": null, 
            "server_port": null, 
            "service_down_action": null, 
            "slow_ramp_time": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "name": "test_pool", 
    "partition": "test_partition", 
    "priority_group_activation": 0
}

TASK [Add pool member] ***************************************************************************************************************************************************
task path: /vagrant/pool_member_issue.yml:23
<172.16.252.51> connection transport is rest
<172.16.252.51> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<172.16.252.51> EXEC /bin/sh -c 'echo ~vagrant && sleep 0'
<172.16.252.51> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.81-54282655428917 `" && echo ansible-tmp-1535209219.81-54282655428917="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.81-54282655428917 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool_member.py
<172.16.252.51> PUT /home/vagrant/.ansible/tmp/ansible-local-11247lepylU/tmpx98THz TO /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.81-54282655428917/bigip_pool_member.py
<172.16.252.51> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.81-54282655428917/ /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.81-54282655428917/bigip_pool_member.py && sleep 0'
<172.16.252.51> EXEC /bin/sh -c '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.81-54282655428917/bigip_pool_member.py && sleep 0'
<172.16.252.51> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1535209219.81-54282655428917/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_99__SO/ansible_module_bigip_pool_member.py", line 904, in main
    results = mm.exec_module()
  File "/tmp/ansible_99__SO/ansible_module_bigip_pool_member.py", line 622, in exec_module
    changed = self.present()
  File "/tmp/ansible_99__SO/ansible_module_bigip_pool_member.py", line 647, in present
    return self.create()
  File "/tmp/ansible_99__SO/ansible_module_bigip_pool_member.py", line 759, in create
    if self.want.name and not any(x for x in [self.want.address, self.want.fqdn_name]):
  File "/tmp/ansible_99__SO/ansible_module_bigip_pool_member.py", line 440, in address
    "The specified 'address' value is not a valid IP address."

fatal: [f5-demo-1.local]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "address": null, 
            "connection_limit": null, 
            "description": null, 
            "fqdn": null, 
            "fqdn_auto_populate": null, 
            "monitor_state": null, 
            "name": "test_node", 
            "partition": "test_partition", 
            "password": null, 
            "pool": "test_pool", 
            "port": 8080, 
            "preserve_node": null, 
            "priority_group": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "172.16.252.51", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "ratio": null, 
            "reuse_nodes": true, 
            "server": null, 
            "server_port": null, 
            "session_state": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "msg": "The specified 'address' value is not a valid IP address."
}
	to retry, use: --limit @/vagrant/pool_member_issue.retry

PLAY RECAP ***************************************************************************************************************************************************************
f5-demo-1.local            : ok=2    changed=2    unreachable=0    failed=1   
```

##### POSSIBLE ROOT CAUSE
When adding existing nodes to a pool, and the route domain is not 0, the IP-address returned to the function is `x.x.x.x%y` - where `y` is the route domain ID.

In the call to [`is_valid_ip`](https://github.com/F5Networks/f5-ansible/blob/673286e285ba9e2656af72adf7ed33e6f2379ab9/library/modules/bigip_pool_member.py#L387) in `bigip_pool_member` the input does not seem to be cleaned from `%y`. Which makes the function return false and the address error to be raised.

**Comment by amsinha2** [comment]
bump

**Comment by lukaszsedek** [comment]
Can you try with `reuse_nodes: no` in bigip_pool_member task?

**Comment by lindeskar** [comment]
I added `reuse_nodes: no` to bigip_pool_member, removed all F5 configuration, ran the playbook, and got a new error:

```
TASK [Add pool member] **********************************************************************************************************************************************************************************
task path: /vagrant/pool_member_issue.yml:23
<172.16.252.51> connection transport is rest
<172.16.252.51> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<172.16.252.51> EXEC /bin/sh -c 'echo ~vagrant && sleep 0'
<172.16.252.51> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1535463525.61-38360065330237 `" && echo ansible-tmp-1535463525.61-38360065330237="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1535463525.61-38360065330237 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool_member.py
<172.16.252.51> PUT /home/vagrant/.ansible/tmp/ansible-local-11643pS_nOK/tmp6C8I9H TO /home/vagrant/.ansible/tmp/ansible-tmp-1535463525.61-38360065330237/bigip_pool_member.py
<172.16.252.51> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1535463525.61-38360065330237/ /home/vagrant/.ansible/tmp/ansible-tmp-1535463525.61-38360065330237/bigip_pool_member.py && sleep 0'
<172.16.252.51> EXEC /bin/sh -c '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1535463525.61-38360065330237/bigip_pool_member.py && sleep 0'
<172.16.252.51> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1535463525.61-38360065330237/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_sdB6lj/ansible_module_bigip_pool_member.py", line 904, in main
    results = mm.exec_module()
  File "/tmp/ansible_sdB6lj/ansible_module_bigip_pool_member.py", line 622, in exec_module
    changed = self.present()
  File "/tmp/ansible_sdB6lj/ansible_module_bigip_pool_member.py", line 647, in present
    return self.create()
  File "/tmp/ansible_sdB6lj/ansible_module_bigip_pool_member.py", line 760, in create
    self._set_host_by_name()
  File "/tmp/ansible_sdB6lj/ansible_module_bigip_pool_member.py", line 699, in _set_host_by_name
    "'name' is neither a valid IP address or FQDN name."

fatal: [f5-demo-1.local]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "address": null, 
            "connection_limit": null, 
            "description": null, 
            "fqdn": null, 
            "fqdn_auto_populate": null, 
            "monitor_state": null, 
            "name": "test_node", 
            "partition": "test_partition", 
            "password": null, 
            "pool": "test_pool", 
            "port": 8080, 
            "preserve_node": null, 
            "priority_group": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "172.16.252.51", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "ratio": null, 
            "reuse_nodes": false, 
            "server": null, 
            "server_port": null, 
            "session_state": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "msg": "'name' is neither a valid IP address or FQDN name."
}
	to retry, use: --limit @/vagrant/pool_member_issue.retry

PLAY RECAP **********************************************************************************************************************************************************************************************
f5-demo-1.local            : ok=2    changed=2    unreachable=0    failed=1   
```

**Comment by hatchepsut** [comment]
I have a small fix for this issue that seem to work for ipv4 addresses in version 2.6.3. Not sure how to go forward though. Can someone give me a pointer?

**Comment by caphrim007** [comment]
@hatchepsut submit PRs to this repository here

**Comment by rdvn** [comment]
This small fix strips RD from pool member definition. This won't fix this issue, but it creates another one.

**Comment by DerrickTJ** [comment]
Also running into the same issue with Ansible 2.7.

As mentioned above, you can create the nodes within the bigip_pool_member but as soon as you have to reuse that member it errors out again.

`TASK [Add nodes to pool] ********************************************************************************************************
changed: [1.1.1.1] => (item={u'f5_node_name': u'sdc1-v', u'f5_node_ip': u'69.69.69.69', u'f5_pool': u'SDC_445', u'f5_node_port': 445})
changed: [1.1.1.1] => (item={u'f5_node_name': u'sdc2-v', u'f5_node_ip': u'69.69.69.70', u'f5_pool': u'SDC_445', u'f5_node_port': 445})
failed: [1.1.1.1] (item={u'f5_node_name': u'sdc1-v', u'f5_node_ip': u'69.69.69.69', u'f5_pool': u'SDC_137', u'f5_node_port': 137}) => {"changed": false, "item": {"f5_node_ip": "69.69.69.69", "f5_node_name": "sdc1-v", "f5_node_port": 137, "f5_pool": "SDC_137"}, "msg": "The specified 'address' value is not a valid IP address."}
failed: [1.1.1.1] (item={u'f5_node_name': u'sdc2-v', u'f5_node_ip': u'69.69.69.70', u'f5_pool': u'SDC_137', u'f5_node_port': 137}) => {"changed": false, "item": {"f5_node_ip": "69.69.69.70", "f5_node_name": "sdc2-v", "f5_node_port": 137, "f5_pool": "SDC_137"}, "msg": "The specified 'address' value is not a valid IP address."}`

**Comment by caphrim007** [comment]
@DerrickTJ I changed this behavior in pool_member the other day. The code in this repository here should reflect that change if you want to try it

**Comment by DerrickTJ** [comment]
I probably did this wrong. I just grabbed the bigip_pool_member.py file and uploaded to my server. New error. It was the only file I replaced. (I made a backup copy)

```
TASK [Add nodes to pool] ********************************************************************************************************
fatal: [1.1.1.1]: FAILED! => {"msg": "module (bigip_pool_member) is missing interpreter line"}
        to retry, use: --limit @/home/username/PROD_F5_ACI_Playbook.retry

**Comment by DerrickTJ** [comment]
@caphrim007 I've tested with https://galaxy.ansible.com/f5devcentral/f5ansible

Same error as before.
"The specified 'address' value is not a valid IP address."

**Comment by caphrim007** [comment]
@DerrickTJ you need to install the `master` branch of that repo.

ansible-galaxy install --force f5devcentral.f5ansible,master

**Comment by DerrickTJ** [comment]
`- f5devcentral.f5ansible (master) was installed successfully`

`TASK [Gathering Facts] **********************************************************************************************************
ok: [1.1.1.1]

TASK [f5devcentral.f5ansible : Check ansible version] ***************************************************************************
skipping: [1.1.1.1]

TASK [Use VARs from file] *******************************************************************************************************
ok: [1.1.1.1]

TASK [Add nodes to pool] ********************************************************************************************************
ok: [1.1.1.1] => (item={u'f5_node_name': u'sdc1-v', u'f5_node_ip': u'69.69.69.69', u'f5_pool': u'SDC_445', u'f5_node_port': 445})
ok: [1.1.1.1] => (item={u'f5_node_name': u'sdc2-v', u'f5_node_ip': u'69.69.69.70', u'f5_pool': u'SDC_445', u'f5_node_port': 445})
failed: [1.1.1.1] (item={u'f5_node_name': u'sdc1-v', u'f5_node_ip': u'69.69.69.69', u'f5_pool': u'SDC_137', u'f5_node_port': 137}) => {"changed": false, "item": {"f5_node_ip": "69.69.69.69", "f5_node_name": "sdc1-v", "f5_node_port": 137, "f5_pool": "SDC_137"}, "msg": "The specified 'address' value is not a valid IP address."}`

**Comment by DerrickTJ** [comment]
@caphrim007 Sure can! The below is how it currently is setup after reading through a few of these bug reports and what others have tried to do. I usually have the other node module create the nodes first and then just have the pool_member add them. Either way, they produce the same error.

Partition "ACI_DataCenter" has a default route domain set to 30.

VAR file:
```
partition: "ACI_DataCenter"
routedomain: "30"

f5_node_list:
#SDC INFORMATION
# 
  - f5_pool: SDC_445
    f5_node_name: sdc1-v
    f5_node_ip: 69.69.69.69
    f5_node_port: 445
# 
  - f5_pool: SDC_445
    f5_node_name: sdc2-v
    f5_node_ip: 69.69.69.70
    f5_node_port: 445
# 
  - f5_pool: SDC_137
    f5_node_name: sdc1-v
    f5_node_ip: 69.69.69.69
    f5_node_port: 137
# 
  - f5_pool: SDC_137
    f5_node_name: sdc2-v
    f5_node_ip: 69.69.69.70
    f5_node_port: 137
# 
  - f5_pool: SDC_139
    f5_node_name: sdc1-v
    f5_node_ip: 69.69.69.69
    f5_node_port: 139
# 
  - f5_pool: SDC_139
    f5_node_name: sdc2-v
    f5_node_ip: 69.69.69.70
    f5_node_port: 139
```

Playbook snip
```
- name: CORPF5LTM1 VLAN, SelfIP, Nodes, Pools, VIPs, HA Sync
  hosts: 1.1.1.1
  connection: local
  
  roles:
    - role: f5devcentral.f5ansible

  tasks:
      - name: Use VARs from file
        include_vars:
            file: PROD_F5_ACI_VARs.yaml
			
      - name: Add nodes to pool
        when: f5_vipcreation
        bigip_pool_member:
            provider:
              server: "{{ f5_ltm1 }}"
              password: "{{ bigip_password }}"
              user: "{{ bigip_username }}"
              validate_certs: "no"
            partition: "{{ partition }}"
            state: "{{ state }}"
            pool: "{{ appname }}_{{ appenvironment }}_{{ apptype }}_{{ item.f5_pool }}_pool"
            port: "{{ item.f5_node_port }}"
            name: "{{ item.f5_node_name }}"
            host: "{{ item.f5_node_ip }}"
        with_items: "{{ f5_node_list }}" 
```

**Comment by DerrickTJ** [comment]
Thanks @wojtek0806 and @caphrim007. I've tested the update and it is working for me now.

**Comment by DerrickTJ** [comment]
@caphrim007 @wojtek0806 I'm truly sorry and may have jumped the gun on saying this was fixed. It seems to be doing better but it still cannot add nodes to the pool.

If the node is already in the pool, it says it is ok and moves on. It use to error out before. So I assumed it was good. Today I went to create a new node and it failed to join the pool saying the same errors as before: invalid IP address.

```TASK [Add nodes to pool] *****************************************************************************************************************************************************************************************************************
ok: [1.1.1.1] => (item={u'f5_node_name': u'applb1-v', u'f5_node_ip': u'1.1.1.20', u'f5_pool': u'POS_8080', u'f5_node_port': 8080})
ok: [1.1.1.1] => (item={u'f5_node_name': u'applb2-v', u'f5_node_ip': u'1.1.1.21', u'f5_pool': u'POS_8080', u'f5_node_port': 8080})
ok: [1.1.1.1] => (item={u'f5_node_name': u'applb1-v', u'f5_node_ip': u'1.1.1.20', u'f5_pool': u'POS_8443', u'f5_node_port': 8443})
ok: [1.1.1.1] => (item={u'f5_node_name': u'applb2-v', u'f5_node_ip': u'1.1.1.21', u'f5_pool': u'POS_8443', u'f5_node_port': 8443})
ok: [1.1.1.1] => (item={u'f5_node_name': u'mgr1-v', u'f5_node_ip': u'1.1.1.70', u'f5_pool': u'MGR_8091', u'f5_node_port': 8091})
ok: [1.1.1.1] => (item={u'f5_node_name': u'mgr1-v', u'f5_node_ip': u'1.1.1.70', u'f5_pool': u'MGR_61616', u'f5_node_port': 61616})
failed: [1.1.1.1] (item={u'f5_node_name': u'TESTNODE', u'f5_node_ip': u'1.1.1.2', u'f5_pool': u'TEST', u'f5_node_port': 80}) => {"changed": false, "item": {"f5_node_ip": "1.1.1.2", "f5_node_name": "TESTNODE", "f5_node_port": 80, "f5_pool": "TEST"}, "msg": "The specified 'address' value is not a valid IP address."}
```
Task is the same as above and the VAR list is still the same besides the test node was added
```
f5_node_list:
  - f5_pool: TEST
    f5_node_name: TESTNODE
    f5_node_ip: 1.1.1.2
    f5_node_port: 80
```
Create node task:
```
      - name: Creating F5 Server Nodes
        bigip_node:
            provider:
              server: "{{ f5_ltm1 }}"
              password: "{{ vault_f5_admin }}"
              user: "{{ bigip_username }}"
              validate_certs: "no"
            partition: "{{ partition }}"
            state: "{{ state }}"
            name: "{{ item.f5_node_name }}"
            host: "{{ item.f5_node_ip }}"
        with_items: "{{ f5_node_list }}" 
```

**Comment by DerrickTJ** [comment]
@wojtek0806 I probably didn't word this right. The issue is still with bigip_pool_member. I only included the creation of the node above for reference of how the node was created.

The playbook will first create the node with bigip_node. So as far as bigip_pool_member is concerned, the node exists prior to adding the member. The node and pool are part of the same partition.

**Comment by DerrickTJ** [comment]
Partition "ACI_DataCenter" has a default route domain set to 30.
Ansible 2.7.0
Python 2.7.5
Lab F5: 13.1.1.2
PROD F5: 13.1.0.8

I'm running your playbooks against my LAB F5.
I had to comment out the assert module that verified the route domain as it was crashing the playbook. I manually verified the the RD and partiion were created and partition had the correct route domain.

first repro:
```
[root@ansible Lab]# ansible-playbook LAB_F5_testrequest1.yaml -vvvv
ansible-playbook 2.7.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
No config file found; using defaults
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: LAB_F5_testrequest1.yaml *******************************************************************************************************************************************************************************************************
1 plays in LAB_F5_testrequest1.yaml

PLAY [Adding nodes to pool within RD] ****************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create test RD 4321] ***************************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest1.yaml:17
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703308.84-233085793296904 `" && echo ansible-tmp-1541703308.84-233085793296904="` echo /root/.ansible/tmp/ansible-tmp-1541703308.84-233085793296904 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_routedomain.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-29822VhF2kC/tmpeAOOJ2 TO /root/.ansible/tmp/ansible-tmp-1541703308.84-233085793296904/AnsiballZ_bigip_routedomain.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703308.84-233085793296904/ /root/.ansible/tmp/ansible-tmp-1541703308.84-233085793296904/AnsiballZ_bigip_routedomain.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703308.84-233085793296904/AnsiballZ_bigip_routedomain.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703308.84-233085793296904/ > /dev/null 2>&1 && sleep 0'
ok: [10.253.95.5] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "bwc_policy": null, 
            "connection_limit": null, 
            "description": null, 
            "flow_eviction_policy": null, 
            "id": 4321, 
            "name": "test-rd", 
            "parent": null, 
            "partition": "Common", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "routing_protocol": null, 
            "server": null, 
            "server_port": null, 
            "service_policy": null, 
            "state": "present", 
            "strict": null, 
            "transport": null, 
            "user": null, 
            "validate_certs": null, 
            "vlans": null
        }
    }
}

TASK [Create test partition RD 4321] *****************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest1.yaml:23
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703309.65-162646174293027 `" && echo ansible-tmp-1541703309.65-162646174293027="` echo /root/.ansible/tmp/ansible-tmp-1541703309.65-162646174293027 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_partition.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-29822VhF2kC/tmpNwFat4 TO /root/.ansible/tmp/ansible-tmp-1541703309.65-162646174293027/AnsiballZ_bigip_partition.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703309.65-162646174293027/ /root/.ansible/tmp/ansible-tmp-1541703309.65-162646174293027/AnsiballZ_bigip_partition.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703309.65-162646174293027/AnsiballZ_bigip_partition.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703309.65-162646174293027/ > /dev/null 2>&1 && sleep 0'
ok: [10.253.95.5] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "description": null, 
            "name": "test_partition", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "route_domain": 4321, 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }
}

TASK [Verify Parition RD 4321] ***********************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest1.yaml:29
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703310.44-41740789296653 `" && echo ansible-tmp-1541703310.44-41740789296653="` echo /root/.ansible/tmp/ansible-tmp-1541703310.44-41740789296653 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_device_facts.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-29822VhF2kC/tmpaH7Lx6 TO /root/.ansible/tmp/ansible-tmp-1541703310.44-41740789296653/AnsiballZ_bigip_device_facts.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703310.44-41740789296653/ /root/.ansible/tmp/ansible-tmp-1541703310.44-41740789296653/AnsiballZ_bigip_device_facts.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703310.44-41740789296653/AnsiballZ_bigip_device_facts.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703310.44-41740789296653/ > /dev/null 2>&1 && sleep 0'
changed: [10.253.95.5] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "gather_subset": [
                "partitions"
            ], 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "server": null, 
            "server_port": null, 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "partitions": [
        {
            "default_route_domain": 0, 
            "description": "Repository for system objects and shared objects.", 
            "full_path": "Common", 
            "name": "Common"
        }, 
        {
            "default_route_domain": 4321, 
            "full_path": "test_partition", 
            "name": "test_partition"
        }
    ]
}

TASK [Create node RD 4321] ***************************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest1.yaml:41
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703311.69-206927046066481 `" && echo ansible-tmp-1541703311.69-206927046066481="` echo /root/.ansible/tmp/ansible-tmp-1541703311.69-206927046066481 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_node.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-29822VhF2kC/tmpgrk4Gn TO /root/.ansible/tmp/ansible-tmp-1541703311.69-206927046066481/AnsiballZ_bigip_node.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703311.69-206927046066481/ /root/.ansible/tmp/ansible-tmp-1541703311.69-206927046066481/AnsiballZ_bigip_node.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703311.69-206927046066481/AnsiballZ_bigip_node.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703311.69-206927046066481/ > /dev/null 2>&1 && sleep 0'
changed: [10.253.95.5] => {
    "changed": true, 
    "fqdn": {
        "autopopulate": "enabled", 
        "downInterval": "5", 
        "interval": "3600"
    }, 
    "fqdn_address_type": "ipv4", 
    "fqdn_auto_populate": "enabled", 
    "fqdn_down_interval": "5", 
    "fqdn_up_interval": "3600", 
    "invocation": {
        "module_args": {
            "address": "1.2.3.4", 
            "auth_provider": null, 
            "connection_limit": null, 
            "description": null, 
            "dynamic_ratio": null, 
            "fqdn": null, 
            "fqdn_address_type": null, 
            "fqdn_auto_populate": null, 
            "fqdn_down_interval": null, 
            "fqdn_up_interval": null, 
            "monitor_type": null, 
            "monitors": null, 
            "name": "test_node", 
            "partition": "test_partition", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "rate_limit": null, 
            "ratio": null, 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "ratio": 1, 
    "session": "user-enabled", 
    "state": "user-up"
}

TASK [Create pool RD 4321] ***************************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest1.yaml:48
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703312.55-161647249216493 `" && echo ansible-tmp-1541703312.55-161647249216493="` echo /root/.ansible/tmp/ansible-tmp-1541703312.55-161647249216493 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-29822VhF2kC/tmpWh95Nk TO /root/.ansible/tmp/ansible-tmp-1541703312.55-161647249216493/AnsiballZ_bigip_pool.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703312.55-161647249216493/ /root/.ansible/tmp/ansible-tmp-1541703312.55-161647249216493/AnsiballZ_bigip_pool.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703312.55-161647249216493/AnsiballZ_bigip_pool.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703312.55-161647249216493/ > /dev/null 2>&1 && sleep 0'
changed: [10.253.95.5] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "description": null, 
            "lb_method": null, 
            "metadata": null, 
            "monitor_type": null, 
            "monitors": null, 
            "name": "test_pool", 
            "partition": "test_partition", 
            "password": null, 
            "priority_group_activation": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "reselect_tries": null, 
            "server": null, 
            "server_port": null, 
            "service_down_action": null, 
            "slow_ramp_time": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "name": "test_pool", 
    "partition": "test_partition", 
    "priority_group_activation": 0
}

TASK [Add pool member RD 4321] ***********************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest1.yaml:54
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703313.37-9347613837047 `" && echo ansible-tmp-1541703313.37-9347613837047="` echo /root/.ansible/tmp/ansible-tmp-1541703313.37-9347613837047 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool_member.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-29822VhF2kC/tmp5cOs6M TO /root/.ansible/tmp/ansible-tmp-1541703313.37-9347613837047/AnsiballZ_bigip_pool_member.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703313.37-9347613837047/ /root/.ansible/tmp/ansible-tmp-1541703313.37-9347613837047/AnsiballZ_bigip_pool_member.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703313.37-9347613837047/AnsiballZ_bigip_pool_member.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703313.37-9347613837047/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_pool_member_payload_TBHzFz/__main__.py", line 834, in main
    results = mm.exec_module()
  File "/tmp/ansible_bigip_pool_member_payload_TBHzFz/__main__.py", line 578, in exec_module
    changed = self.present()
  File "/tmp/ansible_bigip_pool_member_payload_TBHzFz/__main__.py", line 603, in present
    return self.create()
  File "/tmp/ansible_bigip_pool_member_payload_TBHzFz/__main__.py", line 702, in create
    if self.want.name and not any(x for x in [self.want.address, self.want.fqdn_name]):
  File "/tmp/ansible_bigip_pool_member_payload_TBHzFz/__main__.py", line 390, in address
    "The specified 'address' value is not a valid IP address."
fatal: [10.253.95.5]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "address": "1.2.3.4", 
            "auth_provider": null, 
            "connection_limit": null, 
            "description": null, 
            "fqdn": null, 
            "fqdn_auto_populate": null, 
            "host": "1.2.3.4", 
            "name": "test_node", 
            "partition": "test_partition", 
            "password": null, 
            "pool": "test_pool", 
            "port": 8080, 
            "preserve_node": null, 
            "priority_group": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "ratio": null, 
            "reuse_nodes": true, 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "msg": "The specified 'address' value is not a valid IP address."
}
        to retry, use: --limit @/home/COMPANY/derrick/Lab/LAB_F5_testrequest1.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
10.253.95.5                : ok=5    changed=3    unreachable=0    failed=1 
```

Second repo:
```
[root@ansible Lab]# ansible-playbook LAB_F5_testrequest2.yaml -vvvv
ansible-playbook 2.7.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
No config file found; using defaults
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: LAB_F5_testrequest2.yaml *******************************************************************************************************************************************************************************************************
1 plays in LAB_F5_testrequest2.yaml

PLAY [Adding nodes to pool in different RD] **********************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create test RD 1234] ***************************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest2.yaml:15
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703783.0-94578721298851 `" && echo ansible-tmp-1541703783.0-94578721298851="` echo /root/.ansible/tmp/ansible-tmp-1541703783.0-94578721298851 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_routedomain.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-31018TT12l8/tmpUH62tx TO /root/.ansible/tmp/ansible-tmp-1541703783.0-94578721298851/AnsiballZ_bigip_routedomain.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703783.0-94578721298851/ /root/.ansible/tmp/ansible-tmp-1541703783.0-94578721298851/AnsiballZ_bigip_routedomain.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703783.0-94578721298851/AnsiballZ_bigip_routedomain.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703783.0-94578721298851/ > /dev/null 2>&1 && sleep 0'
ok: [10.253.95.5] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "bwc_policy": null, 
            "connection_limit": null, 
            "description": null, 
            "flow_eviction_policy": null, 
            "id": 1234, 
            "name": "test-rd-2", 
            "parent": null, 
            "partition": "Common", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "routing_protocol": null, 
            "server": null, 
            "server_port": null, 
            "service_policy": null, 
            "state": "present", 
            "strict": null, 
            "transport": null, 
            "user": null, 
            "validate_certs": null, 
            "vlans": null
        }
    }
}

TASK [Create test partition] *************************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest2.yaml:21
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703783.79-32037720680499 `" && echo ansible-tmp-1541703783.79-32037720680499="` echo /root/.ansible/tmp/ansible-tmp-1541703783.79-32037720680499 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_partition.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-31018TT12l8/tmpNz_33V TO /root/.ansible/tmp/ansible-tmp-1541703783.79-32037720680499/AnsiballZ_bigip_partition.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703783.79-32037720680499/ /root/.ansible/tmp/ansible-tmp-1541703783.79-32037720680499/AnsiballZ_bigip_partition.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703783.79-32037720680499/AnsiballZ_bigip_partition.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703783.79-32037720680499/ > /dev/null 2>&1 && sleep 0'
ok: [10.253.95.5] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "description": null, 
            "name": "test_partition_2", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "route_domain": null, 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }
}

TASK [Create node RD 1234] ***************************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest2.yaml:26
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703784.57-275558313385378 `" && echo ansible-tmp-1541703784.57-275558313385378="` echo /root/.ansible/tmp/ansible-tmp-1541703784.57-275558313385378 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_node.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-31018TT12l8/tmpm6G277 TO /root/.ansible/tmp/ansible-tmp-1541703784.57-275558313385378/AnsiballZ_bigip_node.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703784.57-275558313385378/ /root/.ansible/tmp/ansible-tmp-1541703784.57-275558313385378/AnsiballZ_bigip_node.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703784.57-275558313385378/AnsiballZ_bigip_node.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703784.57-275558313385378/ > /dev/null 2>&1 && sleep 0'
ok: [10.253.95.5] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "address": "1.2.3.4%1234", 
            "auth_provider": null, 
            "connection_limit": null, 
            "description": null, 
            "dynamic_ratio": null, 
            "fqdn": null, 
            "fqdn_address_type": null, 
            "fqdn_auto_populate": null, 
            "fqdn_down_interval": null, 
            "fqdn_up_interval": null, 
            "monitor_type": null, 
            "monitors": null, 
            "name": "test_node_2", 
            "partition": "test_partition_2", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "rate_limit": null, 
            "ratio": null, 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }
}

TASK [Create pool RD 1234] ***************************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest2.yaml:33
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703785.35-229398081876796 `" && echo ansible-tmp-1541703785.35-229398081876796="` echo /root/.ansible/tmp/ansible-tmp-1541703785.35-229398081876796 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-31018TT12l8/tmpyVojpF TO /root/.ansible/tmp/ansible-tmp-1541703785.35-229398081876796/AnsiballZ_bigip_pool.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703785.35-229398081876796/ /root/.ansible/tmp/ansible-tmp-1541703785.35-229398081876796/AnsiballZ_bigip_pool.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703785.35-229398081876796/AnsiballZ_bigip_pool.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703785.35-229398081876796/ > /dev/null 2>&1 && sleep 0'
ok: [10.253.95.5] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "description": null, 
            "lb_method": null, 
            "metadata": null, 
            "monitor_type": null, 
            "monitors": null, 
            "name": "test_pool_2", 
            "partition": "test_partition_2", 
            "password": null, 
            "priority_group_activation": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "reselect_tries": null, 
            "server": null, 
            "server_port": null, 
            "service_down_action": null, 
            "slow_ramp_time": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "partition": "Common"
}

TASK [Add pool member RD 1234] ***********************************************************************************************************************************************************************************************************
task path: /home/COMPANY/derrick/Lab/LAB_F5_testrequest2.yaml:39
<10.253.95.5> connection transport is rest
<10.253.95.5> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.253.95.5> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1541703786.19-7495056369828 `" && echo ansible-tmp-1541703786.19-7495056369828="` echo /root/.ansible/tmp/ansible-tmp-1541703786.19-7495056369828 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool_member.py
<10.253.95.5> PUT /root/.ansible/tmp/ansible-local-31018TT12l8/tmpRnVdRa TO /root/.ansible/tmp/ansible-tmp-1541703786.19-7495056369828/AnsiballZ_bigip_pool_member.py
<10.253.95.5> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1541703786.19-7495056369828/ /root/.ansible/tmp/ansible-tmp-1541703786.19-7495056369828/AnsiballZ_bigip_pool_member.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1541703786.19-7495056369828/AnsiballZ_bigip_pool_member.py && sleep 0'
<10.253.95.5> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1541703786.19-7495056369828/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_pool_member_payload_igub51/__main__.py", line 834, in main
    results = mm.exec_module()
  File "/tmp/ansible_bigip_pool_member_payload_igub51/__main__.py", line 578, in exec_module
    changed = self.present()
  File "/tmp/ansible_bigip_pool_member_payload_igub51/__main__.py", line 603, in present
    return self.create()
  File "/tmp/ansible_bigip_pool_member_payload_igub51/__main__.py", line 702, in create
    if self.want.name and not any(x for x in [self.want.address, self.want.fqdn_name]):
  File "/tmp/ansible_bigip_pool_member_payload_igub51/__main__.py", line 390, in address
    "The specified 'address' value is not a valid IP address."
fatal: [10.253.95.5]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "address": "1.2.3.4%1234", 
            "auth_provider": null, 
            "connection_limit": null, 
            "description": null, 
            "fqdn": null, 
            "fqdn_auto_populate": null, 
            "host": "1.2.3.4%1234", 
            "name": "test_node_2", 
            "partition": "test_partition_2", 
            "password": null, 
            "pool": "test_pool_2", 
            "port": 8080, 
            "preserve_node": null, 
            "priority_group": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.253.95.5", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "ratio": null, 
            "reuse_nodes": true, 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "msg": "The specified 'address' value is not a valid IP address."
}
        to retry, use: --limit @/home/COMPANY/derrick/Lab/LAB_F5_testrequest2.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
10.253.95.5                : ok=4    changed=0    unreachable=0    failed=1 
```

**Comment by onurbrc** [comment]
Hi, 

I'm having the same problem with bigip_pool_member when I try to add a new already created node into a pool. 

I've trying different ways to represent the same behavior as the tmsh command : 
``` 
modify ltm pool Pool-FlowTest-8080 members add { opfwt01:8080 }
```
Like "Node List" option passing by GUI in pool/mmebers. 

As suggested, I can use bigip_pool_member to create nodes without using bigip_node, this works very well. But, in my case, sometimes we want to reuse created nodes inside different pools in the same device.

**Comment by wojtek0806** [comment]
@onurbrc

This is a different issue, when you create nodes you create a server without port attached, when you reuse them as pool_members you attach a port to the node, simply think of the pool member as services running on your nodes.

 You should be able to reuse the exiting nodes to add them to the different pools as members, provided they are on the same partitions, as the bigip_pool_member module does not use separate partitions when you attempting to reuse existing nodes, it assumes the node you are looking is on the same partition.

**Comment by wojtek0806** [comment]
Once we have the sufficient data from @DerrickTJ and determine this is indeed a bug I will open a new issue. for now I will close this, but we can continue discussion here

**Comment by onurbrc** [comment]
@wojtek0806, 

The nodes that I'm trying to attach to a two or more pools are in the same partition that I'm creating the pools. The routedomain is also linked to the partition.

**Comment by DerrickTJ** [comment]
@wojtek0806 Are you referring to this? ```ansible-galaxy install f5devcentral.f5ansible``` or ```ansible-galaxy install --force f5devcentral.f5ansible,master``` I thought the only way to use those was by using the dev role:
```
 roles:
    - role: f5devcentral.f5ansible
```

Sorry, you threw out some new terms I'm not use to hearing.

**Comment by wojtek0806** [comment]
@DerrickTJ what i meant was to clone f5-ansible repository and use the contents of the library for your ansible modules code, which what the ansible galaxy role you have is doing, the problem is that the role does not have recent changes so we need to do a new release of it. I will see if we can update it today so you can download it from ansible galaxy and retest.

**Comment by wojtek0806** [comment]
@onurbrc 
Unfortunately this is not supported by the module at this time. Feel free to open an issue to request this enhancement.

**Comment by DerrickTJ** [comment]
@wojtek0806 Ah ok that makes sense. Thank you.

**Comment by vikas7999** [comment]
I have same error as cannot add existing node in route domain 2 to pool member. Giving me error Invaid IP address 3.3.3.3%2.  I verified ansible playbook was able to create the proper node in route domain2. 
Is this feature supported on ansible pool member.

**Comment by sgetache** [comment]
Having the same issue. Anyone here was able to figure out if there is a fix ?

**Comment by DerrickTJ** [comment]
> Having the same issue. Anyone here was able to figure out if there is a fix ?

Have you tried with Ansible 2.8? Apparently this was fixed in that release. I have yet to try it though.

**Comment by sgetache** [comment]
Derrick,

Thanks for quick reply.

I’ll upgrade to 2.8 and try again.
--------------------------------------------
On Thu, 6/6/19, Derrick Johnson <notifications@github.com> wrote:

 Subject: Re: [F5Networks/f5-ansible] bigip_pool_member can't add existing node in route domain to a pool (#887)
 To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>
 Cc: "sgetache" <Surafel_is@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Thursday, June 6, 2019, 12:46 PM
 
 
 Having the same issue. Anyone here was able to figure out
 if there is a fix ?
 
 Have you tried with Ansible 2.8? Apparently this was
 fixed in that release. I have yet to try it though.
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by DerrickTJ** [comment]
> Derrick, Thanks for quick reply. I’ll upgrade to 2.8 and try again.

Let us know the results please.

**Comment by sgetache** [comment]
Derrick,

Upgraded ansible to v2.8. Getting same message “No JSON object could be decoded”. This only happens when I append %3 within pools and virtual servers for route domain.

Example?

Pools: x.x.x.x%3
Destination vs: x.x.x.x%3

Otherwise, when %3 is removed, the playbook runs successfully.

please note adding nodes with %3 route always worked (ansible 2.7 or 2.8)


Is there anything additional I reed to introduce in the playbook ?

Please help ?

Thanks.



--------------------------------------------
On Fri, 6/7/19, Derrick Johnson <notifications@github.com> wrote:

 Subject: Re: [F5Networks/f5-ansible] bigip_pool_member can't add existing node in route domain to a pool (#887)
 To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>
 Cc: "sgetache" <Surafel_is@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Friday, June 7, 2019, 12:59 PM
 
 
 Derrick, Thanks for quick reply. I’ll upgrade to 2.8
 and try again.
 
 Let us know the results please.
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by sgetache** [comment]
Still not able to resolve this issue, even with ansible 2.8.  Anyone here had any luck ?

--------------------------------------------
On Mon, 6/10/19, Surafel Getachew <surafel_is@yahoo.com> wrote:

 Subject: Re: [F5Networks/f5-ansible] bigip_pool_member can't add existing node in route domain to a pool (#887)
 To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>, "F5Networks/f5-ansible" <reply@reply.github.com>
 Cc: "sgetache" <Surafel_is@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Monday, June 10, 2019, 2:14 PM
 
 Derrick,
 
 Upgraded ansible to v2.8. Getting same
 message “No JSON object could be decoded”. This only
 happens when I append %3 within pools and virtual servers
 for route domain.
 
 Example?
 
 Pools: x.x.x.x%3
 Destination vs: x.x.x.x%3
 
 Otherwise, when %3 is removed, the
 playbook runs successfully.
 
 please note adding nodes with %3 route
 always worked (ansible 2.7 or 2.8)
 
 
 Is there anything additional I reed to
 introduce in the playbook ?
 
 Please help ?
 
 Thanks.
 
 
 
 --------------------------------------------
 On Fri, 6/7/19, Derrick Johnson <notifications@github.com>
 wrote:
 
  Subject: Re: [F5Networks/f5-ansible]
 bigip_pool_member can't add existing node in route domain to
 a pool (#887)
  To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>
  Cc: "sgetache" <Surafel_is@yahoo.com>,
 "Comment" <comment@noreply.github.com>
  Date: Friday, June 7, 2019, 12:59 PM
  
  
  Derrick, Thanks for quick reply.
 I’ll upgrade to 2.8
  and try again.
  
  Let us know the results please.
  
  —
  You are receiving this because you
 commented.
  Reply to this email directly, view
  it on GitHub, or mute
  the thread.

**Comment by DerrickTJ** [comment]
Good to hear, thank you for letting us know.
